apiVersion: v2
name: lareira-miniflux
description: pleme-lareira home-services chart for Miniflux (RSS reader).
type: application
version: 0.1.0
appVersion: "2.2.4"
dependencies:
  - {name: pleme-lib, version: ">=0.18.0", repository: "file://../pleme-lib"}
  - {name: pleme-lareira, version: ">=0.1.0", repository: "file://../pleme-lareira"}
