{{- include "pleme-lib.serviceaccount" . }}
{{- if .Values.builderServiceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.builderServiceAccount.name | default (printf "%s-builder" (include "pleme-lib.fullname" .)) }}
  namespace: {{ include "pleme-lib.namespace" . }}
  labels:
    {{- include "pleme-lib.labels" . | nindent 4 }}
    app.kubernetes.io/component: builder
  {{- with .Values.builderServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
