{{- if .Values.webhookSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: tatara-github-watcher-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pleme-lib.labels" (index .Subcharts "pleme-microservice") | nindent 4 }}
type: Opaque
stringData:
  secret: {{ .Values.webhookSecret.value | quote }}
{{- end }}
