apiVersion: v2
name: convergence-controller
description: Convergence process controller — spawns K8s clusters as convergence processes from CRDs
type: application
version: 0.1.1
appVersion: "0.1.0"

dependencies:
  - name: pleme-lib
    version: "~0.10.0"
    repository: "file://../pleme-lib"
