apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lava-operator
rules:
  - apiGroups:
      - lava.pleme.io
    resources:
      - lavaarchitectures
      - lavaarchitectures/status
      - remediationpolicies
      - lavaarchitecturedependencies
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - create
      - patch
