{{- if .Values.enabled }}
{{- if .Values.selfSignedIssuer.enabled }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.selfSignedIssuer.name }}
  labels:
    {{- include "lareira-cert-manager.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
{{- if .Values.acmeIssuer.enabled }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.acmeIssuer.name }}
  labels:
    {{- include "lareira-cert-manager.labels" . | nindent 4 }}
spec:
  acme:
    email: {{ .Values.acmeIssuer.email | quote }}
    server: {{ .Values.acmeIssuer.server | quote }}
    privateKeySecretRef:
      name: {{ printf "%s-account-key" .Values.acmeIssuer.name }}
    solvers:
      - {{ .Values.acmeIssuer.solver | toYaml | nindent 8 | trim }}
{{- end }}
{{- end }}
