{{/*
pleme-lib.delivery — Transport slice (CIA).

Renders NATS JetStream consumer configuration as a ConfigMap, providing
consistent delivery guarantee semantics across all chart consumers.

Delivery tiers:
  best_effort — memory buffer, drop on overflow (metrics, debug)
  durable     — disk buffer, block on overflow (important events)
  guaranteed  — NATS JetStream persistence + DLQ (transactional)

Usage in a chart's templates/delivery.yaml:
  {{- include "pleme-lib.delivery" . }}

Values:
  delivery:
    enabled: true
    tier: durable
    nats:
      url: "nats://nats.nats.svc:4222"
      stream: BUILD
      consumer: builder
    buffer:
      type: disk
      maxSize: 536870912
      whenFull: block
    retry:
      maxDeliver: 5
      ackWait: "30s"
    dlq:
      enabled: false
      stream: ""
*/}}

{{- define "pleme-lib.delivery" -}}
{{- if .Values.delivery }}
{{- if .Values.delivery.enabled }}
{{- $fullname := include "pleme-lib.fullname" . }}
{{- $tier := default "durable" .Values.delivery.tier }}

{{/* ── Tier presets ─────────────────────────────────────────────── */}}
{{- $bufferType := "disk" }}
{{- $bufferMaxSize := 536870912 }}
{{- $whenFull := "block" }}
{{- $maxDeliver := 5 }}
{{- $ackWait := "30s" }}

{{- if eq $tier "best_effort" }}
  {{- $bufferType = "memory" }}
  {{- $bufferMaxSize = 10000 }}
  {{- $whenFull = "drop_newest" }}
  {{- $maxDeliver = 1 }}
  {{- $ackWait = "10s" }}
{{- else if eq $tier "guaranteed" }}
  {{- $bufferType = "disk" }}
  {{- $bufferMaxSize = 5368709120 }}
  {{- $whenFull = "block" }}
  {{- $maxDeliver = -1 }}
  {{- $ackWait = "300s" }}
{{- end }}

{{/* Override presets with explicit values */}}
{{- if .Values.delivery.buffer }}
  {{- if .Values.delivery.buffer.type }}
    {{- $bufferType = .Values.delivery.buffer.type }}
  {{- end }}
  {{- if .Values.delivery.buffer.maxSize }}
    {{- $bufferMaxSize = .Values.delivery.buffer.maxSize }}
  {{- end }}
  {{- if .Values.delivery.buffer.whenFull }}
    {{- $whenFull = .Values.delivery.buffer.whenFull }}
  {{- end }}
{{- end }}
{{- if .Values.delivery.retry }}
  {{- if .Values.delivery.retry.maxDeliver }}
    {{- $maxDeliver = .Values.delivery.retry.maxDeliver }}
  {{- end }}
  {{- if .Values.delivery.retry.ackWait }}
    {{- $ackWait = .Values.delivery.retry.ackWait }}
  {{- end }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}-delivery
  labels:
    {{- include "pleme-lib.labels" . | nindent 4 }}
    pleme.io/delivery-tier: {{ $tier }}
data:
  delivery.yaml: |
    # Delivery configuration — tier: {{ $tier }}
    # Generated by pleme-lib.delivery template
    tier: {{ $tier }}
    nats:
      url: {{ default "nats://nats.nats.svc:4222" (.Values.delivery.nats).url | quote }}
      stream: {{ default "" (.Values.delivery.nats).stream | quote }}
      consumer: {{ default "" (.Values.delivery.nats).consumer | quote }}
    buffer:
      type: {{ $bufferType }}
      max_size: {{ $bufferMaxSize }}
      when_full: {{ $whenFull }}
    retry:
      max_deliver: {{ $maxDeliver }}
      ack_wait: {{ $ackWait | quote }}
    {{- if .Values.delivery.dlq }}
    {{- if .Values.delivery.dlq.enabled }}
    dlq:
      enabled: true
      stream: {{ .Values.delivery.dlq.stream | quote }}
    {{- end }}
    {{- end }}

{{- end }}
{{- end }}
{{- end }}
