{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "pleme-nix-builder.fullname" . }}
  labels:
    {{- include "pleme-nix-builder.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    kind: StatefulSet
    name: {{ include "pleme-nix-builder.fullname" . }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  triggers:
    - type: nats-jetstream
      metadata:
        natsServerMonitoringEndpoint: {{ .Values.keda.nats.serverURL | replace "nats://" "" | replace ":4222" ":8222" | quote }}
        stream: {{ .Values.keda.nats.stream | quote }}
        consumer: {{ .Values.keda.nats.consumer | quote }}
        lagThreshold: {{ .Values.keda.nats.lagThreshold | quote }}
        activationLagThreshold: {{ .Values.keda.nats.activationLagThreshold | quote }}
{{- end }}
