apiVersion: v2
name: lareira-stirling-pdf
description: pleme-lareira home-services chart for Stirling-PDF (browser-based PDF tools).
type: application
version: 0.1.0
appVersion: "0.42.0"
dependencies:
  - {name: pleme-lib, version: ">=0.18.0", repository: "file://../pleme-lib"}
  - {name: pleme-lareira, version: ">=0.1.0", repository: "file://../pleme-lareira"}
annotations:
  org.opencontainers.image.source: https://github.com/pleme-io/helmworks
