apiVersion: v2
name: pleme-shinryu
description: DataFusion analytical query plane — ANSI SQL over all Shinryū observability signals
type: application
version: 0.1.4
appVersion: "0.1.0"

dependencies:
  - name: pleme-lib
    version: "~0.15.0"
    repository: "file://../pleme-lib"
