apiVersion: v2
name: pleme-sui
description: "sui (粋) — Rust-native Nix build + cache platform (ro platform)"
type: application
version: 0.2.8
appVersion: "0.2.2"
dependencies:
  - name: pleme-lib
    version: ">=0.18.0"
    repository: "file://../pleme-lib"
