apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pleme-lib.fullname" . }}-tend-config
  namespace: {{ include "pleme-lib.namespace" . }}
  labels:
    {{- include "pleme-lib.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.tendConfig | toYaml | nindent 4 }}
