apiVersion: v2
name: lareira-audiobookshelf
description: pleme-lareira home-services chart for Audiobookshelf (audiobook + podcast server).
type: application
version: 0.1.0
appVersion: "2.17.7"
dependencies:
  - name: pleme-lib
    version: ">=0.18.0"
    repository: "file://../pleme-lib"
  - name: pleme-lareira
    version: ">=0.1.0"
    repository: "file://../pleme-lareira"
annotations:
  org.opencontainers.image.source: https://github.com/pleme-io/helmworks
