apiVersion: v1
kind: Service
metadata:
  name: {{ include "pleme-lib.fullname" . }}-headless
  namespace: {{ include "pleme-lib.namespace" . }}
  labels:
    {{- include "pleme-lib.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
  selector:
    {{- include "pleme-lib.selectorLabels" . | nindent 4 }}
